// Auto-generated by v156_procfs_fd_observability_fix.
#![allow(unused_assignments)]
#![allow(dead_code)]
#![allow(static_mut_refs)]

const MAX_PROCS: usize = 8;
const MAX_FDS: usize = 32;
const PATH_MAX: usize = 96;
const COMM_MAX: usize = 16;
const INIT_PID: u16 = 1;

pub const O_CLOEXEC: u32 = 0x80000;
pub const FD_CLOEXEC: u32 = 1;

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum Errno { NoEnt, BadFd, NoSpace, Inval, Srch, Access }

#[derive(Copy, Clone)]
pub struct ProcSnapshot {
    pub pid: u16,
    pub ppid: u16,
    pub pgid: u16,
    pub sid: u16,
    pub fd_count: usize,
    pub cloexec_count: usize,
    pub cwd_len: usize,
    pub root_len: usize,
}

#[derive(Copy, Clone)]
struct FdEntry {
    used: bool,
    cloexec: bool,
    flags: u32,
    target: [u8; PATH_MAX],
    target_len: usize,
}
impl FdEntry {
    const fn empty() -> Self { Self { used: false, cloexec: false, flags: 0, target: [0; PATH_MAX], target_len: 0 } }
}

#[derive(Copy, Clone)]
struct ProcEntry {
    used: bool,
    pid: u16,
    ppid: u16,
    pgid: u16,
    sid: u16,
    cwd: [u8; PATH_MAX],
    cwd_len: usize,
    root: [u8; PATH_MAX],
    root_len: usize,
    umask: u16,
    comm: [u8; COMM_MAX],
    comm_len: usize,
    fds: [FdEntry; MAX_FDS],
}
impl ProcEntry {
    const fn empty() -> Self {
        Self { used: false, pid: 0, ppid: 0, pgid: 0, sid: 0, cwd: [0; PATH_MAX], cwd_len: 0, root: [0; PATH_MAX], root_len: 0, umask: 0o022, comm: [0; COMM_MAX], comm_len: 0, fds: [FdEntry::empty(); MAX_FDS] }
    }
}

pub struct ProcFsCore {
    procs: [ProcEntry; MAX_PROCS],
    current_pid: u16,
    next_pid: u16,
}

fn bytes_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    let mut i = 0;
    while i < a.len() { if a[i] != b[i] { return false; } i += 1; }
    true
}

fn set_bytes(dst: &mut [u8], len: &mut usize, src: &[u8]) -> Result<(), Errno> {
    if src.len() > dst.len() { return Err(Errno::NoSpace); }
    let mut i = 0;
    while i < dst.len() { dst[i] = 0; i += 1; }
    i = 0;
    while i < src.len() { dst[i] = src[i]; i += 1; }
    *len = src.len();
    Ok(())
}

fn component_is_dot(path: &[u8], start: usize, end: usize) -> bool { end == start + 1 && path[start] == b'.' }
fn component_is_dotdot(path: &[u8], start: usize, end: usize) -> bool { end == start + 2 && path[start] == b'.' && path[start + 1] == b'.' }

fn push_component(out: &mut [u8; PATH_MAX], out_len: &mut usize, path: &[u8], start: usize, end: usize) -> Result<(), Errno> {
    if component_is_dot(path, start, end) { return Ok(()); }
    if component_is_dotdot(path, start, end) {
        if *out_len <= 1 { *out_len = 1; out[0] = b'/'; return Ok(()); }
        let mut pos = *out_len - 1;
        while pos > 0 && out[pos] != b'/' { pos -= 1; }
        if pos == 0 { *out_len = 1; } else { *out_len = pos; }
        return Ok(());
    }
    if *out_len == 0 { out[0] = b'/'; *out_len = 1; }
    if *out_len > 1 { if *out_len >= PATH_MAX { return Err(Errno::NoSpace); } out[*out_len] = b'/'; *out_len += 1; }
    let mut i = start;
    while i < end {
        if *out_len >= PATH_MAX { return Err(Errno::NoSpace); }
        out[*out_len] = path[i];
        *out_len += 1;
        i += 1;
    }
    Ok(())
}

fn normalize_path(base: &[u8], path: &[u8], out: &mut [u8; PATH_MAX], out_len: &mut usize) -> Result<(), Errno> {
    let mut temp = [0u8; PATH_MAX];
    let mut len = 0usize;
    temp[0] = b'/';
    len = 1;
    if path.is_empty() { return Err(Errno::NoEnt); }
    if path[0] != b'/' {
        let mut pos = 0usize;
        while pos < base.len() {
            while pos < base.len() && base[pos] == b'/' { pos += 1; }
            let start = pos;
            while pos < base.len() && base[pos] != b'/' { pos += 1; }
            if pos > start { push_component(&mut temp, &mut len, base, start, pos)?; }
        }
    }
    let mut pos = 0usize;
    while pos < path.len() {
        while pos < path.len() && path[pos] == b'/' { pos += 1; }
        let start = pos;
        while pos < path.len() && path[pos] != b'/' { pos += 1; }
        if pos > start { push_component(&mut temp, &mut len, path, start, pos)?; }
    }
    if len == 0 { temp[0] = b'/'; len = 1; }
    set_bytes(out, out_len, &temp[..len])
}

impl ProcFsCore {
    pub const fn new() -> Self { Self { procs: [ProcEntry::empty(); MAX_PROCS], current_pid: INIT_PID, next_pid: 2 } }

    pub fn reset(&mut self) {
        self.procs = [ProcEntry::empty(); MAX_PROCS];
        self.current_pid = INIT_PID;
        self.next_pid = 2;
        self.procs[0].used = true;
        self.procs[0].pid = INIT_PID;
        self.procs[0].ppid = 0;
        self.procs[0].pgid = INIT_PID;
        self.procs[0].sid = INIT_PID;
        let _ = set_bytes(&mut self.procs[0].cwd, &mut self.procs[0].cwd_len, b"/");
        let _ = set_bytes(&mut self.procs[0].root, &mut self.procs[0].root_len, b"/");
        let _ = set_bytes(&mut self.procs[0].comm, &mut self.procs[0].comm_len, b"init");
        let _ = self.install_fd_for(0, 0, b"/dev/stdin", 0, false);
        let _ = self.install_fd_for(0, 1, b"/dev/stdout", 0, false);
        let _ = self.install_fd_for(0, 2, b"/dev/stderr", 0, false);
    }

    fn proc_index(&self, pid: u16) -> Result<usize, Errno> {
        let mut i = 0usize;
        while i < MAX_PROCS { if self.procs[i].used && self.procs[i].pid == pid { return Ok(i); } i += 1; }
        Err(Errno::Srch)
    }

    fn current_index(&self) -> Result<usize, Errno> { self.proc_index(self.current_pid) }

    fn install_fd_for(&mut self, proc_idx: usize, fd: usize, target: &[u8], flags: u32, cloexec: bool) -> Result<isize, Errno> {
        if fd >= MAX_FDS { return Err(Errno::BadFd); }
        self.procs[proc_idx].fds[fd] = FdEntry::empty();
        self.procs[proc_idx].fds[fd].used = true;
        self.procs[proc_idx].fds[fd].flags = flags;
        self.procs[proc_idx].fds[fd].cloexec = cloexec;
        set_bytes(&mut self.procs[proc_idx].fds[fd].target, &mut self.procs[proc_idx].fds[fd].target_len, target)?;
        Ok(fd as isize)
    }

    fn alloc_fd_for(&mut self, proc_idx: usize, target: &[u8], flags: u32, cloexec: bool) -> Result<isize, Errno> {
        let mut fd = 3usize;
        while fd < MAX_FDS {
            if !self.procs[proc_idx].fds[fd].used { return self.install_fd_for(proc_idx, fd, target, flags, cloexec); }
            fd += 1;
        }
        Err(Errno::NoSpace)
    }

    pub fn set_comm(&mut self, name: &[u8]) -> Result<(), Errno> {
        let idx = self.current_index()?;
        set_bytes(&mut self.procs[idx].comm, &mut self.procs[idx].comm_len, name)
    }

    pub fn chdir(&mut self, path: &[u8]) -> Result<(), Errno> {
        let idx = self.current_index()?;
        let base_len = self.procs[idx].cwd_len;
        let mut out = [0u8; PATH_MAX];
        let mut len = 0usize;
        normalize_path(&self.procs[idx].cwd[..base_len], path, &mut out, &mut len)?;
        set_bytes(&mut self.procs[idx].cwd, &mut self.procs[idx].cwd_len, &out[..len])
    }

    pub fn chroot(&mut self, path: &[u8]) -> Result<(), Errno> {
        let idx = self.current_index()?;
        let base_len = self.procs[idx].cwd_len;
        let mut out = [0u8; PATH_MAX];
        let mut len = 0usize;
        normalize_path(&self.procs[idx].cwd[..base_len], path, &mut out, &mut len)?;
        set_bytes(&mut self.procs[idx].root, &mut self.procs[idx].root_len, &out[..len])
    }

    pub fn open_proc_fd(&mut self, path: &[u8], flags: u32) -> Result<isize, Errno> {
        let idx = self.current_index()?;
        let base_len = self.procs[idx].cwd_len;
        let mut out = [0u8; PATH_MAX];
        let mut len = 0usize;
        normalize_path(&self.procs[idx].cwd[..base_len], path, &mut out, &mut len)?;
        self.alloc_fd_for(idx, &out[..len], flags, (flags & O_CLOEXEC) != 0)
    }

    pub fn dup3(&mut self, old_fd: isize, new_fd: isize, cloexec: bool) -> Result<isize, Errno> {
        if old_fd < 0 || new_fd < 0 || old_fd == new_fd { return Err(Errno::BadFd); }
        let idx = self.current_index()?;
        let old = old_fd as usize;
        let newf = new_fd as usize;
        if old >= MAX_FDS || newf >= MAX_FDS || !self.procs[idx].fds[old].used { return Err(Errno::BadFd); }
        self.procs[idx].fds[newf] = self.procs[idx].fds[old];
        self.procs[idx].fds[newf].cloexec = cloexec;
        Ok(new_fd)
    }

    pub fn set_fd_cloexec(&mut self, fd: isize, cloexec: bool) -> Result<(), Errno> {
        if fd < 0 { return Err(Errno::BadFd); }
        let idx = self.current_index()?;
        let f = fd as usize;
        if f >= MAX_FDS || !self.procs[idx].fds[f].used { return Err(Errno::BadFd); }
        self.procs[idx].fds[f].cloexec = cloexec;
        Ok(())
    }

    pub fn fork_current(&mut self) -> Result<u16, Errno> {
        let parent_idx = self.current_index()?;
        let mut child_idx = 0usize;
        while child_idx < MAX_PROCS && self.procs[child_idx].used { child_idx += 1; }
        if child_idx >= MAX_PROCS { return Err(Errno::NoSpace); }
        let pid = self.next_pid;
        self.next_pid = self.next_pid.wrapping_add(1);
        self.procs[child_idx] = self.procs[parent_idx];
        self.procs[child_idx].pid = pid;
        self.procs[child_idx].ppid = self.procs[parent_idx].pid;
        self.procs[child_idx].used = true;
        Ok(pid)
    }

    pub fn switch_to(&mut self, pid: u16) -> Result<(), Errno> {
        let _ = self.proc_index(pid)?;
        self.current_pid = pid;
        Ok(())
    }

    pub fn setpgid(&mut self, pid: u16, pgid: u16) -> Result<(), Errno> {
        let idx = self.proc_index(pid)?;
        self.procs[idx].pgid = if pgid == 0 { pid } else { pgid };
        Ok(())
    }

    pub fn setsid_current(&mut self) -> Result<u16, Errno> {
        let idx = self.current_index()?;
        let pid = self.procs[idx].pid;
        self.procs[idx].sid = pid;
        self.procs[idx].pgid = pid;
        Ok(pid)
    }

    pub fn exec_current(&mut self, comm: &[u8]) -> Result<usize, Errno> {
        let idx = self.current_index()?;
        set_bytes(&mut self.procs[idx].comm, &mut self.procs[idx].comm_len, comm)?;
        let mut closed = 0usize;
        let mut fd = 0usize;
        while fd < MAX_FDS {
            if self.procs[idx].fds[fd].used && self.procs[idx].fds[fd].cloexec {
                self.procs[idx].fds[fd] = FdEntry::empty();
                closed += 1;
            }
            fd += 1;
        }
        Ok(closed)
    }

    pub fn close_range(&mut self, first: usize, last: usize) -> Result<usize, Errno> {
        if first > last || last >= MAX_FDS { return Err(Errno::Inval); }
        let idx = self.current_index()?;
        let mut closed = 0usize;
        let mut fd = first;
        while fd <= last {
            if self.procs[idx].fds[fd].used { self.procs[idx].fds[fd] = FdEntry::empty(); closed += 1; }
            fd += 1;
        }
        Ok(closed)
    }

    pub fn proc_self_fd_readlink(&self, fd: isize, out: &mut [u8]) -> Result<usize, Errno> {
        if fd < 0 { return Err(Errno::BadFd); }
        let idx = self.current_index()?;
        let f = fd as usize;
        if f >= MAX_FDS || !self.procs[idx].fds[f].used { return Err(Errno::BadFd); }
        let mut i = 0usize;
        while i < out.len() && i < self.procs[idx].fds[f].target_len { out[i] = self.procs[idx].fds[f].target[i]; i += 1; }
        Ok(i)
    }

    pub fn proc_pid_fd_readlink(&self, pid: u16, fd: isize, out: &mut [u8]) -> Result<usize, Errno> {
        if fd < 0 { return Err(Errno::BadFd); }
        let idx = self.proc_index(pid)?;
        let f = fd as usize;
        if f >= MAX_FDS || !self.procs[idx].fds[f].used { return Err(Errno::BadFd); }
        let mut i = 0usize;
        while i < out.len() && i < self.procs[idx].fds[f].target_len { out[i] = self.procs[idx].fds[f].target[i]; i += 1; }
        Ok(i)
    }

    pub fn snapshot(&self, pid: u16) -> Result<ProcSnapshot, Errno> {
        let idx = self.proc_index(pid)?;
        let mut fd_count = 0usize;
        let mut cloexec_count = 0usize;
        let mut fd = 0usize;
        while fd < MAX_FDS {
            if self.procs[idx].fds[fd].used { fd_count += 1; if self.procs[idx].fds[fd].cloexec { cloexec_count += 1; } }
            fd += 1;
        }
        Ok(ProcSnapshot { pid: self.procs[idx].pid, ppid: self.procs[idx].ppid, pgid: self.procs[idx].pgid, sid: self.procs[idx].sid, fd_count, cloexec_count, cwd_len: self.procs[idx].cwd_len, root_len: self.procs[idx].root_len })
    }

    pub fn current_cwd_matches(&self, expect: &[u8]) -> Result<(), Errno> {
        let idx = self.current_index()?;
        if bytes_eq(&self.procs[idx].cwd[..self.procs[idx].cwd_len], expect) { Ok(()) } else { Err(Errno::Inval) }
    }

    pub fn current_root_matches(&self, expect: &[u8]) -> Result<(), Errno> {
        let idx = self.current_index()?;
        if bytes_eq(&self.procs[idx].root[..self.procs[idx].root_len], expect) { Ok(()) } else { Err(Errno::Inval) }
    }
}

static mut V156_PROCFS: ProcFsCore = ProcFsCore::new();

pub fn run_v156_procfs_fd_observability_scenario() -> Option<&'static str> {
    let k = unsafe { &mut V156_PROCFS };
    k.reset();
    if k.set_comm(b"init-v156").is_err() { return Some("set_comm_init"); }
    if k.chdir(b"/v156root").is_err() { return Some("chdir_root"); }
    if k.current_cwd_matches(b"/v156root").is_err() { return Some("cwd_root_match"); }
    if k.chroot(b"/").is_err() { return Some("chroot_slash"); }
    if k.current_root_matches(b"/").is_err() { return Some("root_match"); }

    let fd_a = match k.open_proc_fd(b"logs/./a.txt", 0) { Ok(fd) => fd, Err(_) => return Some("open_fd_a") };
    let fd_b = match k.open_proc_fd(b"logs/../logs/b.txt", O_CLOEXEC) { Ok(fd) => fd, Err(_) => return Some("open_fd_b_cloexec") };
    if fd_a == fd_b { return Some("fd_alloc_distinct"); }
    if k.dup3(fd_a, 10, true).ok() != Some(10) { return Some("dup3_cloexec"); }
    if k.set_fd_cloexec(fd_a, false).is_err() { return Some("set_fd_cloexec_false"); }

    let mut link = [0u8; PATH_MAX];
    let link_len = match k.proc_self_fd_readlink(10, &mut link) { Ok(n) => n, Err(_) => return Some("proc_self_fd_10") };
    if !bytes_eq(&link[..link_len], b"/v156root/logs/a.txt") { return Some("proc_self_fd_target"); }

    let child = match k.fork_current() { Ok(pid) => pid, Err(_) => return Some("fork_child") };
    if k.switch_to(child).is_err() { return Some("switch_child"); }
    let before_exec = match k.snapshot(child) { Ok(s) => s, Err(_) => return Some("snapshot_child_before") };
    if before_exec.ppid != INIT_PID || before_exec.fd_count < 6 || before_exec.cloexec_count < 2 { return Some("inherit_fd_snapshot"); }
    if k.setpgid(child, 0).is_err() { return Some("setpgid_child") };
    if k.setsid_current().ok() != Some(child) { return Some("setsid_child"); }
    let session = match k.snapshot(child) { Ok(s) => s, Err(_) => return Some("snapshot_session") };
    if session.sid != child || session.pgid != child { return Some("session_ids"); }
    if k.chdir(b"work/../workdir").is_err() { return Some("child_chdir_dotdot"); }
    if k.current_cwd_matches(b"/v156root/workdir").is_err() { return Some("child_cwd_normalized"); }

    let closed = match k.exec_current(b"child-v156") { Ok(n) => n, Err(_) => return Some("exec_child") };
    if closed < 2 { return Some("exec_closes_cloexec"); }
    if k.proc_self_fd_readlink(fd_b, &mut link).err() != Some(Errno::BadFd) { return Some("cloexec_fd_b_closed"); }
    if k.proc_self_fd_readlink(10, &mut link).err() != Some(Errno::BadFd) { return Some("cloexec_dup_closed"); }
    let alive_len = match k.proc_self_fd_readlink(fd_a, &mut link) { Ok(n) => n, Err(_) => return Some("noncloexec_fd_a_alive") };
    if !bytes_eq(&link[..alive_len], b"/v156root/logs/a.txt") { return Some("noncloexec_target_after_exec"); }
    let after_exec = match k.snapshot(child) { Ok(s) => s, Err(_) => return Some("snapshot_after_exec") };
    if after_exec.fd_count < 4 || after_exec.cloexec_count != 0 || after_exec.cwd_len == 0 || after_exec.root_len == 0 { return Some("post_exec_snapshot"); }

    let parent = INIT_PID;
    if k.proc_pid_fd_readlink(parent, fd_a, &mut link).is_err() { return Some("proc_pid_parent_fd") };
    if k.close_range(3, 3).ok() != Some(1) { return Some("close_range_one"); }
    if k.proc_self_fd_readlink(fd_a, &mut link).err() != Some(Errno::BadFd) { return Some("close_range_effect"); }
    None
}
