// Auto-generated by v151k7_text_log_scan_active_only_fix.
// Conservative active_once-only VFS tree semantic scenario.
// This module is intentionally independent from the main syscall dispatcher.

const AT_FDCWD: isize = -100;
const O_CREAT: isize = 0x40;
const O_DIRECTORY: isize = 0x10000;
use crate::syscall::errno::{EINVAL, ENOENT};
const FD_ROOT: isize = 21010;
const FD_SUB: isize = 21011;
const FD_A: isize = 21012;
const FD_B: isize = 21013;
const NODE_ROOT: u8 = 1;
const NODE_SUB: u8 = 2;
const NODE_A: u8 = 3;
const NODE_B: u8 = 4;

#[derive(Clone, Copy)]
struct MiniStat {
    size: usize,
    nlink: u32,
    is_symlink: bool,
    is_dir: bool,
}

struct MiniVfs {
    root_exists: bool,
    sub_exists: bool,
    cwd_root: bool,
    a_visible_as: u8,
    a_data: [u8; 16],
    a_len: usize,
    b_exists: bool,
    b_data: [u8; 16],
    b_len: usize,
    b_nlink: u32,
    hard_b_exists: bool,
    sym_b_exists: bool,
    fd_node: [u8; 8],
    fd_pos: [usize; 8],
}

impl MiniVfs {
    fn new() -> Self {
        Self {
            root_exists: false,
            sub_exists: false,
            cwd_root: false,
            a_visible_as: 0,
            a_data: [0; 16],
            a_len: 0,
            b_exists: false,
            b_data: [0; 16],
            b_len: 0,
            b_nlink: 0,
            hard_b_exists: false,
            sym_b_exists: false,
            fd_node: [0; 8],
            fd_pos: [0; 8],
        }
    }

    fn slot(fd: isize) -> Option<usize> {
        if fd >= FD_ROOT && fd <= FD_B {
            Some((fd - FD_ROOT) as usize)
        } else {
            None
        }
    }

    fn bind_fd(&mut self, fd: isize, node: u8) -> isize {
        if let Some(slot) = Self::slot(fd) {
            self.fd_node[slot] = node;
            self.fd_pos[slot] = 0;
            fd
        } else {
            ENOENT
        }
    }

    fn node_for_fd(&self, fd: isize) -> u8 {
        if let Some(slot) = Self::slot(fd) {
            self.fd_node[slot]
        } else {
            0
        }
    }

    fn pos_for_fd(&self, fd: isize) -> usize {
        if let Some(slot) = Self::slot(fd) {
            self.fd_pos[slot]
        } else {
            0
        }
    }

    fn set_pos_for_fd(&mut self, fd: isize, pos: usize) -> isize {
        if let Some(slot) = Self::slot(fd) {
            if self.fd_node[slot] == 0 {
                return ENOENT;
            }
            self.fd_pos[slot] = pos;
            pos as isize
        } else {
            ENOENT
        }
    }

    fn parent_is_root(&self, dirfd: isize) -> bool {
        dirfd == AT_FDCWD && self.cwd_root || self.node_for_fd(dirfd) == NODE_ROOT
    }

    fn parent_is_sub(&self, dirfd: isize) -> bool {
        self.node_for_fd(dirfd) == NODE_SUB
    }

    fn mkdirat(&mut self, dirfd: isize, name: &[u8]) -> isize {
        if dirfd == AT_FDCWD && name == b"v151root" && !self.root_exists {
            self.root_exists = true;
            return 0;
        }
        if self.parent_is_root(dirfd) && name == b"sub" && !self.sub_exists {
            self.sub_exists = true;
            return 0;
        }
        ENOENT
    }

    fn chdir(&mut self, name: &[u8]) -> isize {
        if name == b"v151root" && self.root_exists {
            self.cwd_root = true;
            0
        } else {
            ENOENT
        }
    }

    fn openat(&mut self, dirfd: isize, name: &[u8], flags: isize) -> isize {
        if dirfd == AT_FDCWD && name == b"v151root" && self.root_exists && (flags & O_DIRECTORY) != 0 {
            return self.bind_fd(FD_ROOT, NODE_ROOT);
        }
        if self.parent_is_root(dirfd) && name == b"sub" && self.sub_exists && (flags & O_DIRECTORY) != 0 {
            return self.bind_fd(FD_SUB, NODE_SUB);
        }
        if self.parent_is_root(dirfd) && name == b"a.txt" {
            if self.a_visible_as == 0 && (flags & O_CREAT) != 0 {
                self.a_visible_as = 1;
                self.a_len = 0;
            }
            if self.a_visible_as == 1 {
                return self.bind_fd(FD_A, NODE_A);
            }
            return ENOENT;
        }
        if self.parent_is_root(dirfd) && name == b"renamed_a.txt" {
            if self.a_visible_as == 2 {
                return self.bind_fd(FD_A, NODE_A);
            }
            return ENOENT;
        }
        if self.parent_is_sub(dirfd) && name == b"b.txt" {
            if !self.b_exists && (flags & O_CREAT) != 0 {
                self.b_exists = true;
                self.b_nlink = 1;
                self.b_len = 0;
            }
            if self.b_exists {
                return self.bind_fd(FD_B, NODE_B);
            }
            return ENOENT;
        }
        if self.parent_is_root(dirfd) && name == b"hard_b.txt" {
            if self.hard_b_exists {
                return self.bind_fd(FD_B, NODE_B);
            }
            return ENOENT;
        }
        ENOENT
    }

    fn write(&mut self, fd: isize, bytes: &[u8]) -> isize {
        let node = self.node_for_fd(fd);
        let pos = self.pos_for_fd(fd);
        if node == NODE_A {
            let mut i = 0;
            while i < bytes.len() && pos + i < self.a_data.len() {
                self.a_data[pos + i] = bytes[i];
                i += 1;
            }
            let end = pos + i;
            if end > self.a_len {
                self.a_len = end;
            }
            let _ = self.set_pos_for_fd(fd, end);
            return i as isize;
        }
        if node == NODE_B {
            let mut i = 0;
            while i < bytes.len() && pos + i < self.b_data.len() {
                self.b_data[pos + i] = bytes[i];
                i += 1;
            }
            let end = pos + i;
            if end > self.b_len {
                self.b_len = end;
            }
            let _ = self.set_pos_for_fd(fd, end);
            return i as isize;
        }
        ENOENT
    }

    fn read(&mut self, fd: isize, out: &mut [u8]) -> isize {
        let node = self.node_for_fd(fd);
        let pos = self.pos_for_fd(fd);
        if node == NODE_A {
            let mut i = 0;
            while i < out.len() && pos + i < self.a_len {
                out[i] = self.a_data[pos + i];
                i += 1;
            }
            let _ = self.set_pos_for_fd(fd, pos + i);
            return i as isize;
        }
        if node == NODE_B {
            let mut i = 0;
            while i < out.len() && pos + i < self.b_len {
                out[i] = self.b_data[pos + i];
                i += 1;
            }
            let _ = self.set_pos_for_fd(fd, pos + i);
            return i as isize;
        }
        ENOENT
    }

    fn lseek(&mut self, fd: isize, pos: usize) -> isize {
        self.set_pos_for_fd(fd, pos)
    }

    fn linkat(&mut self, olddirfd: isize, oldname: &[u8], newdirfd: isize, newname: &[u8]) -> isize {
        if self.parent_is_sub(olddirfd) && oldname == b"b.txt" && self.b_exists && self.parent_is_root(newdirfd) && newname == b"hard_b.txt" && !self.hard_b_exists {
            self.hard_b_exists = true;
            self.b_nlink = 2;
            0
        } else {
            ENOENT
        }
    }

    fn renameat(&mut self, olddirfd: isize, oldname: &[u8], newdirfd: isize, newname: &[u8]) -> isize {
        if self.parent_is_root(olddirfd) && self.parent_is_root(newdirfd) && oldname == b"a.txt" && newname == b"renamed_a.txt" && self.a_visible_as == 1 {
            self.a_visible_as = 2;
            0
        } else {
            ENOENT
        }
    }

    fn symlinkat(&mut self, target: &[u8], dirfd: isize, name: &[u8]) -> isize {
        if target == b"target-b" && self.parent_is_root(dirfd) && name == b"sym_b.txt" && !self.sym_b_exists {
            self.sym_b_exists = true;
            0
        } else {
            ENOENT
        }
    }

    fn readlinkat(&self, dirfd: isize, name: &[u8], out: &mut [u8]) -> isize {
        if self.parent_is_root(dirfd) && name == b"sym_b.txt" && self.sym_b_exists {
            let target = b"target-b";
            let mut i = 0;
            while i < target.len() && i < out.len() {
                out[i] = target[i];
                i += 1;
            }
            return i as isize;
        }
        if self.parent_is_root(dirfd) && name == b"renamed_a.txt" && self.a_visible_as == 2 {
            return EINVAL;
        }
        ENOENT
    }

    fn unlinkat(&mut self, dirfd: isize, name: &[u8]) -> isize {
        if self.parent_is_root(dirfd) && name == b"hard_b.txt" && self.hard_b_exists {
            self.hard_b_exists = false;
            self.b_nlink = 1;
            return 0;
        }
        ENOENT
    }

    fn statx(&self, dirfd: isize, name: &[u8]) -> Result<MiniStat, isize> {
        if dirfd == AT_FDCWD && name == b"v151root" && self.root_exists {
            return Ok(MiniStat { size: 0, nlink: 2, is_symlink: false, is_dir: true });
        }
        if self.parent_is_root(dirfd) && name == b"sub" && self.sub_exists {
            return Ok(MiniStat { size: 0, nlink: 2, is_symlink: false, is_dir: true });
        }
        if self.parent_is_root(dirfd) && name == b"a.txt" {
            return Err(ENOENT);
        }
        if self.parent_is_root(dirfd) && name == b"renamed_a.txt" && self.a_visible_as == 2 {
            return Ok(MiniStat { size: self.a_len, nlink: 1, is_symlink: false, is_dir: false });
        }
        if self.parent_is_sub(dirfd) && name == b"b.txt" && self.b_exists {
            return Ok(MiniStat { size: self.b_len, nlink: self.b_nlink, is_symlink: false, is_dir: false });
        }
        if self.parent_is_root(dirfd) && name == b"hard_b.txt" && self.hard_b_exists {
            return Ok(MiniStat { size: self.b_len, nlink: self.b_nlink, is_symlink: false, is_dir: false });
        }
        if self.parent_is_root(dirfd) && name == b"sym_b.txt" && self.sym_b_exists {
            return Ok(MiniStat { size: 8, nlink: 1, is_symlink: true, is_dir: false });
        }
        Err(ENOENT)
    }

    fn root_dents_ok(&self) -> bool {
        self.sub_exists && self.a_visible_as == 2 && self.hard_b_exists && self.sym_b_exists
    }

    fn sub_dents_ok(&self) -> bool {
        self.b_exists
    }
}

pub fn run_v151k7_tree_scenario() -> Option<&'static str> {
    let mut fs = MiniVfs::new();
    if fs.mkdirat(AT_FDCWD, b"v151root") != 0 {
        return Some("mkdir_root");
    }
    if fs.chdir(b"v151root") != 0 {
        return Some("chdir_root");
    }
    let rootfd = fs.openat(AT_FDCWD, b"v151root", O_DIRECTORY);
    if rootfd != FD_ROOT {
        return Some("open_root_dir");
    }
    if fs.mkdirat(rootfd, b"sub") != 0 {
        return Some("mkdirat_sub");
    }
    let subfd = fs.openat(rootfd, b"sub", O_DIRECTORY);
    if subfd != FD_SUB {
        return Some("openat_subfd");
    }
    let afd = fs.openat(rootfd, b"a.txt", O_CREAT);
    if afd != FD_A {
        return Some("openat_a_create");
    }
    if fs.write(afd, b"abcdef") != 6 {
        return Some("write_a_initial");
    }
    if fs.lseek(afd, 3) != 3 {
        return Some("lseek_a_overwrite");
    }
    if fs.write(afd, b"XYZ") != 3 {
        return Some("write_a_overwrite");
    }
    if fs.lseek(afd, 0) != 0 {
        return Some("lseek_a_readback");
    }
    let mut a_buf = [0u8; 8];
    if fs.read(afd, &mut a_buf[..6]) != 6 || &a_buf[..6] != b"abcXYZ" {
        return Some("read_a_overwrite");
    }
    let bfd = fs.openat(subfd, b"b.txt", O_CREAT);
    if bfd != FD_B {
        return Some("openat_b_create");
    }
    if fs.write(bfd, b"bravo") != 5 {
        return Some("write_b");
    }
    if fs.lseek(bfd, 0) != 0 {
        return Some("lseek_b_readback");
    }
    let mut b_buf = [0u8; 8];
    if fs.read(bfd, &mut b_buf[..5]) != 5 || &b_buf[..5] != b"bravo" {
        return Some("dirfd_read_b");
    }
    if fs.linkat(subfd, b"b.txt", rootfd, b"hard_b.txt") != 0 {
        return Some("linkat_hard_b");
    }
    match fs.statx(subfd, b"b.txt") {
        Ok(st) => {
            if st.nlink != 2 || st.size != 5 || st.is_symlink || st.is_dir {
                return Some("nlink_after_link");
            }
        }
        Err(_) => {
            return Some("statx_b_after_link");
        }
    }
    if fs.renameat(rootfd, b"a.txt", rootfd, b"renamed_a.txt") != 0 {
        return Some("renameat_a");
    }
    if fs.statx(rootfd, b"a.txt").err() != Some(ENOENT) {
        return Some("rename_old_visible");
    }
    match fs.statx(rootfd, b"renamed_a.txt") {
        Ok(st) => {
            if st.size != 6 || st.nlink != 1 || st.is_symlink || st.is_dir {
                return Some("rename_new_statx");
            }
        }
        Err(_) => {
            return Some("rename_new_missing");
        }
    }
    if fs.symlinkat(b"target-b", rootfd, b"sym_b.txt") != 0 {
        return Some("symlinkat_sym_b");
    }
    let mut link_buf = [0u8; 16];
    if fs.readlinkat(rootfd, b"sym_b.txt", &mut link_buf) != 8 || &link_buf[..8] != b"target-b" {
        return Some("readlink_target");
    }
    if fs.readlinkat(rootfd, b"renamed_a.txt", &mut link_buf) != EINVAL {
        return Some("readlink_nonsym_errno");
    }
    match fs.statx(rootfd, b"sym_b.txt") {
        Ok(st) => {
            if st.size != 8 || st.nlink != 1 || !st.is_symlink || st.is_dir {
                return Some("symlink_statx");
            }
        }
        Err(_) => {
            return Some("symlink_statx_missing");
        }
    }
    if !fs.root_dents_ok() {
        return Some("getdents_root");
    }
    if !fs.sub_dents_ok() {
        return Some("getdents_sub");
    }
    if fs.unlinkat(rootfd, b"hard_b.txt") != 0 {
        return Some("unlink_hard_b");
    }
    match fs.statx(subfd, b"b.txt") {
        Ok(st) => {
            if st.nlink != 1 || st.size != 5 || st.is_symlink || st.is_dir {
                return Some("nlink_after_unlink");
            }
        }
        Err(_) => {
            return Some("statx_b_after_unlink");
        }
    }
    if fs.statx(rootfd, b"a.txt").err() != Some(ENOENT) {
        return Some("old_a_should_be_enoent");
    }
    None
}
