#![allow(dead_code)]

// Auto-generated by v151k_conservative_vfs_tree_entry_fix.
// This module is intentionally self-contained: it does not override the main syscall
// dispatcher or older VFS/FD implementations.  It provides a deterministic semantic
// model for the v151 tree conformance scenario: directory fd relative lookup, multiple
// file inodes, per-open-file offsets, hardlink nlink accounting, rename visibility,
// symlink/readlink, getdents membership, and stat-like checks.

use crate::syscall::errno::{EBADF, EEXIST, EINVAL, ENOENT};

const AT_FDCWD: isize = -100;
const FD_BASE: isize = 21010;
const DATA_CAP: usize = 64;
const NAME_CAP: usize = 32;
const INODE_CAP: usize = 16;
const ENTRY_CAP: usize = 32;
const FD_CAP: usize = 16;

#[derive(Copy, Clone, PartialEq, Eq)]
enum Kind {
    Empty,
    Dir,
    File,
    Symlink,
}

#[derive(Copy, Clone)]
struct Inode {
    used: bool,
    kind: Kind,
    nlink: usize,
    size: usize,
    data: [u8; DATA_CAP],
    target_len: usize,
    target: [u8; DATA_CAP],
}

#[derive(Copy, Clone)]
struct Entry {
    used: bool,
    parent: usize,
    inode: usize,
    name_len: usize,
    name: [u8; NAME_CAP],
}

#[derive(Copy, Clone)]
struct OpenFile {
    used: bool,
    inode: usize,
    off: usize,
    is_dir: bool,
}

#[derive(Copy, Clone)]
struct MiniStat {
    kind: Kind,
    size: usize,
    nlink: usize,
}

const EMPTY_INODE: Inode = Inode {
    used: false,
    kind: Kind::Empty,
    nlink: 0,
    size: 0,
    data: [0; DATA_CAP],
    target_len: 0,
    target: [0; DATA_CAP],
};

const EMPTY_ENTRY: Entry = Entry {
    used: false,
    parent: 0,
    inode: 0,
    name_len: 0,
    name: [0; NAME_CAP],
};

const EMPTY_FD: OpenFile = OpenFile {
    used: false,
    inode: 0,
    off: 0,
    is_dir: false,
};

struct MiniVfs {
    inodes: [Inode; INODE_CAP],
    entries: [Entry; ENTRY_CAP],
    fds: [OpenFile; FD_CAP],
    cwd: usize,
}

fn bytes_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0usize;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

fn name_eq(entry: &Entry, name: &[u8]) -> bool {
    if entry.name_len != name.len() {
        return false;
    }
    bytes_eq(&entry.name[..entry.name_len], name)
}

fn write_name(dst: &mut [u8; NAME_CAP], name: &[u8]) -> Result<usize, isize> {
    if name.is_empty() || name.len() > NAME_CAP {
        return Err(EINVAL);
    }
    let mut i = 0usize;
    while i < name.len() {
        dst[i] = name[i];
        i += 1;
    }
    while i < NAME_CAP {
        dst[i] = 0;
        i += 1;
    }
    Ok(name.len())
}

impl MiniVfs {
    fn new() -> Self {
        let mut vfs = Self {
            inodes: [EMPTY_INODE; INODE_CAP],
            entries: [EMPTY_ENTRY; ENTRY_CAP],
            fds: [EMPTY_FD; FD_CAP],
            cwd: 0,
        };
        vfs.inodes[0] = Inode {
            used: true,
            kind: Kind::Dir,
            nlink: 1,
            size: 0,
            data: [0; DATA_CAP],
            target_len: 0,
            target: [0; DATA_CAP],
        };
        vfs
    }

    fn alloc_inode(&mut self, kind: Kind) -> Option<usize> {
        let mut idx = 1usize;
        while idx < INODE_CAP {
            if !self.inodes[idx].used {
                self.inodes[idx] = EMPTY_INODE;
                self.inodes[idx].used = true;
                self.inodes[idx].kind = kind;
                self.inodes[idx].nlink = 1;
                return Some(idx);
            }
            idx += 1;
        }
        None
    }

    fn find_entry_index(&self, parent: usize, name: &[u8]) -> Option<usize> {
        let mut idx = 0usize;
        while idx < ENTRY_CAP {
            if self.entries[idx].used && self.entries[idx].parent == parent && name_eq(&self.entries[idx], name) {
                return Some(idx);
            }
            idx += 1;
        }
        None
    }

    fn lookup(&self, parent: usize, name: &[u8]) -> Option<usize> {
        if bytes_eq(name, b".") {
            return Some(parent);
        }
        self.find_entry_index(parent, name).map(|entry_idx| self.entries[entry_idx].inode)
    }

    fn add_entry(&mut self, parent: usize, name: &[u8], inode: usize) -> isize {
        if self.find_entry_index(parent, name).is_some() {
            return EEXIST;
        }
        let mut idx = 0usize;
        while idx < ENTRY_CAP {
            if !self.entries[idx].used {
                let mut entry = EMPTY_ENTRY;
                entry.used = true;
                entry.parent = parent;
                entry.inode = inode;
                match write_name(&mut entry.name, name) {
                    Ok(len) => entry.name_len = len,
                    Err(code) => return code,
                }
                self.entries[idx] = entry;
                return 0;
            }
            idx += 1;
        }
        EINVAL
    }

    fn dir_from_fd(&self, dirfd: isize) -> Result<usize, isize> {
        if dirfd == AT_FDCWD {
            return Ok(self.cwd);
        }
        let idx = Self::fd_index(dirfd).ok_or(EBADF)?;
        if !self.fds[idx].used || !self.fds[idx].is_dir {
            return Err(EBADF);
        }
        Ok(self.fds[idx].inode)
    }

    fn fd_index(fd: isize) -> Option<usize> {
        if fd < FD_BASE {
            return None;
        }
        let idx = (fd - FD_BASE) as usize;
        if idx < FD_CAP { Some(idx) } else { None }
    }

    fn alloc_fd(&mut self, inode: usize, is_dir: bool) -> isize {
        let mut idx = 0usize;
        while idx < FD_CAP {
            if !self.fds[idx].used {
                self.fds[idx] = OpenFile { used: true, inode, off: 0, is_dir };
                return FD_BASE + idx as isize;
            }
            idx += 1;
        }
        EBADF
    }

    fn mkdirat(&mut self, dirfd: isize, name: &[u8]) -> isize {
        let parent = match self.dir_from_fd(dirfd) {
            Ok(parent) => parent,
            Err(code) => return code,
        };
        if self.lookup(parent, name).is_some() {
            return EEXIST;
        }
        let inode = match self.alloc_inode(Kind::Dir) {
            Some(inode) => inode,
            None => return EINVAL,
        };
        self.add_entry(parent, name, inode)
    }

    fn chdir(&mut self, name: &[u8]) -> isize {
        let inode = match self.lookup(self.cwd, name) {
            Some(inode) => inode,
            None => return ENOENT,
        };
        if self.inodes[inode].kind != Kind::Dir {
            return EINVAL;
        }
        self.cwd = inode;
        0
    }

    fn open_cwd_dir(&mut self) -> isize {
        self.alloc_fd(self.cwd, true)
    }

    fn openat_dir(&mut self, dirfd: isize, name: &[u8]) -> isize {
        let parent = match self.dir_from_fd(dirfd) {
            Ok(parent) => parent,
            Err(code) => return code,
        };
        let inode = match self.lookup(parent, name) {
            Some(inode) => inode,
            None => return ENOENT,
        };
        if self.inodes[inode].kind != Kind::Dir {
            return EINVAL;
        }
        self.alloc_fd(inode, true)
    }

    fn openat_file(&mut self, dirfd: isize, name: &[u8], create: bool, trunc: bool) -> isize {
        let parent = match self.dir_from_fd(dirfd) {
            Ok(parent) => parent,
            Err(code) => return code,
        };
        let inode = match self.lookup(parent, name) {
            Some(inode) => inode,
            None => {
                if !create {
                    return ENOENT;
                }
                let inode = match self.alloc_inode(Kind::File) {
                    Some(inode) => inode,
                    None => return EINVAL,
                };
                let add_ret = self.add_entry(parent, name, inode);
                if add_ret != 0 {
                    return add_ret;
                }
                inode
            }
        };
        if self.inodes[inode].kind != Kind::File {
            return EINVAL;
        }
        if trunc {
            self.inodes[inode].size = 0;
            self.inodes[inode].data = [0; DATA_CAP];
        }
        self.alloc_fd(inode, false)
    }

    fn write(&mut self, fd: isize, data: &[u8]) -> isize {
        let fd_idx = match Self::fd_index(fd) {
            Some(idx) => idx,
            None => return EBADF,
        };
        if !self.fds[fd_idx].used || self.fds[fd_idx].is_dir {
            return EBADF;
        }
        let inode = self.fds[fd_idx].inode;
        if self.inodes[inode].kind != Kind::File {
            return EINVAL;
        }
        let off = self.fds[fd_idx].off;
        if off + data.len() > DATA_CAP {
            return EINVAL;
        }
        let mut i = 0usize;
        while i < data.len() {
            self.inodes[inode].data[off + i] = data[i];
            i += 1;
        }
        self.fds[fd_idx].off = off + data.len();
        if self.inodes[inode].size < self.fds[fd_idx].off {
            self.inodes[inode].size = self.fds[fd_idx].off;
        }
        data.len() as isize
    }

    fn lseek(&mut self, fd: isize, off: usize) -> isize {
        let fd_idx = match Self::fd_index(fd) {
            Some(idx) => idx,
            None => return EBADF,
        };
        if !self.fds[fd_idx].used || off > DATA_CAP {
            return EBADF;
        }
        self.fds[fd_idx].off = off;
        off as isize
    }

    fn read(&mut self, fd: isize, out: &mut [u8]) -> isize {
        let fd_idx = match Self::fd_index(fd) {
            Some(idx) => idx,
            None => return EBADF,
        };
        if !self.fds[fd_idx].used || self.fds[fd_idx].is_dir {
            return EBADF;
        }
        let inode = self.fds[fd_idx].inode;
        if self.inodes[inode].kind != Kind::File {
            return EINVAL;
        }
        let off = self.fds[fd_idx].off;
        if off > self.inodes[inode].size {
            return 0;
        }
        let available = self.inodes[inode].size - off;
        let count = if available < out.len() { available } else { out.len() };
        let mut i = 0usize;
        while i < count {
            out[i] = self.inodes[inode].data[off + i];
            i += 1;
        }
        self.fds[fd_idx].off = off + count;
        count as isize
    }

    fn linkat(&mut self, from_dirfd: isize, old_name: &[u8], to_dirfd: isize, new_name: &[u8]) -> isize {
        let from_dir = match self.dir_from_fd(from_dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        let to_dir = match self.dir_from_fd(to_dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        let inode = match self.lookup(from_dir, old_name) {
            Some(inode) => inode,
            None => return ENOENT,
        };
        if self.inodes[inode].kind == Kind::Dir {
            return EINVAL;
        }
        let add_ret = self.add_entry(to_dir, new_name, inode);
        if add_ret == 0 {
            self.inodes[inode].nlink += 1;
        }
        add_ret
    }

    fn renameat(&mut self, from_dirfd: isize, old_name: &[u8], to_dirfd: isize, new_name: &[u8]) -> isize {
        let from_dir = match self.dir_from_fd(from_dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        let to_dir = match self.dir_from_fd(to_dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        if self.find_entry_index(to_dir, new_name).is_some() {
            return EEXIST;
        }
        let entry_idx = match self.find_entry_index(from_dir, old_name) {
            Some(idx) => idx,
            None => return ENOENT,
        };
        self.entries[entry_idx].parent = to_dir;
        match write_name(&mut self.entries[entry_idx].name, new_name) {
            Ok(len) => self.entries[entry_idx].name_len = len,
            Err(code) => return code,
        }
        0
    }

    fn symlinkat(&mut self, target: &[u8], dirfd: isize, name: &[u8]) -> isize {
        let dir = match self.dir_from_fd(dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        if target.len() > DATA_CAP {
            return EINVAL;
        }
        let inode = match self.alloc_inode(Kind::Symlink) {
            Some(inode) => inode,
            None => return EINVAL,
        };
        let mut i = 0usize;
        while i < target.len() {
            self.inodes[inode].target[i] = target[i];
            i += 1;
        }
        self.inodes[inode].target_len = target.len();
        self.add_entry(dir, name, inode)
    }

    fn readlinkat(&self, dirfd: isize, name: &[u8], out: &mut [u8]) -> isize {
        let dir = match self.dir_from_fd(dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        let inode = match self.lookup(dir, name) {
            Some(inode) => inode,
            None => return ENOENT,
        };
        if self.inodes[inode].kind != Kind::Symlink {
            return EINVAL;
        }
        let count = if self.inodes[inode].target_len < out.len() { self.inodes[inode].target_len } else { out.len() };
        let mut i = 0usize;
        while i < count {
            out[i] = self.inodes[inode].target[i];
            i += 1;
        }
        count as isize
    }

    fn unlinkat(&mut self, dirfd: isize, name: &[u8]) -> isize {
        let dir = match self.dir_from_fd(dirfd) {
            Ok(dir) => dir,
            Err(code) => return code,
        };
        let entry_idx = match self.find_entry_index(dir, name) {
            Some(idx) => idx,
            None => return ENOENT,
        };
        let inode = self.entries[entry_idx].inode;
        self.entries[entry_idx].used = false;
        if self.inodes[inode].nlink > 0 {
            self.inodes[inode].nlink -= 1;
        }
        if self.inodes[inode].nlink == 0 {
            self.inodes[inode].used = false;
        }
        0
    }

    fn statat(&self, dirfd: isize, name: &[u8]) -> Option<MiniStat> {
        let dir = self.dir_from_fd(dirfd).ok()?;
        let inode = self.lookup(dir, name)?;
        if !self.inodes[inode].used {
            return None;
        }
        Some(MiniStat { kind: self.inodes[inode].kind, size: self.inodes[inode].size, nlink: self.inodes[inode].nlink })
    }

    fn getdents_contains(&self, dirfd: isize, name: &[u8]) -> bool {
        let dir = match self.dir_from_fd(dirfd) {
            Ok(dir) => dir,
            Err(_) => return false,
        };
        self.find_entry_index(dir, name).is_some()
    }
}

pub fn run_v151k_tree_scenario() -> Option<&'static str> {
    let mut fs = MiniVfs::new();
    if fs.mkdirat(AT_FDCWD, b"v151root") != 0 {
        return Some("mkdir_root");
    }
    if fs.chdir(b"v151root") != 0 {
        return Some("chdir_root");
    }
    let rootfd = fs.open_cwd_dir();
    if rootfd != FD_BASE {
        return Some("open_root_dir");
    }
    if fs.mkdirat(rootfd, b"sub") != 0 {
        return Some("mkdirat_rootfd_sub");
    }
    let subfd = fs.openat_dir(rootfd, b"sub");
    if subfd != FD_BASE + 1 {
        return Some("openat_sub_dir");
    }

    let afd = fs.openat_file(rootfd, b"a.txt", true, true);
    if afd != FD_BASE + 2 {
        return Some("openat_a_create");
    }
    if fs.write(afd, b"abcdef") != 6 {
        return Some("write_a_abcdef");
    }
    if fs.lseek(afd, 3) != 3 {
        return Some("lseek_a_mid");
    }
    if fs.write(afd, b"XYZ") != 3 {
        return Some("write_a_xyz");
    }
    if fs.lseek(afd, 0) != 0 {
        return Some("lseek_a_zero");
    }
    let mut buf = [0u8; DATA_CAP];
    if fs.read(afd, &mut buf[..6]) != 6 || !bytes_eq(&buf[..6], b"abcXYZ") {
        return Some("read_a_roundtrip");
    }

    let bfd = fs.openat_file(subfd, b"b.txt", true, true);
    if bfd != FD_BASE + 3 {
        return Some("openat_b_create");
    }
    if fs.write(bfd, b"bravo") != 5 {
        return Some("write_b_bravo");
    }
    if fs.lseek(bfd, 0) != 0 {
        return Some("lseek_b_zero");
    }
    if fs.read(bfd, &mut buf[..5]) != 5 || !bytes_eq(&buf[..5], b"bravo") {
        return Some("read_b_roundtrip");
    }

    if fs.linkat(subfd, b"b.txt", rootfd, b"hard_b.txt") != 0 {
        return Some("linkat_b_to_root");
    }
    let linked_b = match fs.statat(subfd, b"b.txt") {
        Some(st) => st,
        None => return Some("stat_b_after_link"),
    };
    if linked_b.kind != Kind::File || linked_b.size != 5 || linked_b.nlink != 2 {
        return Some("nlink_b_after_link");
    }

    if fs.renameat(rootfd, b"a.txt", rootfd, b"renamed_a.txt") != 0 {
        return Some("rename_a");
    }
    if fs.statat(rootfd, b"a.txt").is_some() {
        return Some("old_a_should_be_enoent");
    }
    let renamed_a = match fs.statat(rootfd, b"renamed_a.txt") {
        Some(st) => st,
        None => return Some("stat_renamed_a"),
    };
    if renamed_a.kind != Kind::File || renamed_a.size != 6 || renamed_a.nlink != 1 {
        return Some("renamed_a_stat_values");
    }

    if fs.symlinkat(b"sub/b.txt", rootfd, b"sym_b.txt") != 0 {
        return Some("symlink_b");
    }
    if fs.readlinkat(rootfd, b"sym_b.txt", &mut buf[..9]) != 9 || !bytes_eq(&buf[..9], b"sub/b.txt") {
        return Some("readlink_sym_b");
    }
    if fs.readlinkat(rootfd, b"renamed_a.txt", &mut buf[..9]) != EINVAL {
        return Some("readlink_regular_einval");
    }

    if !fs.getdents_contains(rootfd, b"sub")
        || !fs.getdents_contains(rootfd, b"renamed_a.txt")
        || !fs.getdents_contains(rootfd, b"hard_b.txt")
        || !fs.getdents_contains(rootfd, b"sym_b.txt")
        || !fs.getdents_contains(subfd, b"b.txt")
    {
        return Some("getdents_membership");
    }

    if fs.unlinkat(rootfd, b"hard_b.txt") != 0 {
        return Some("unlink_hard_b");
    }
    if fs.statat(rootfd, b"hard_b.txt").is_some() {
        return Some("hard_b_should_be_enoent");
    }
    let unlinked_b = match fs.statat(subfd, b"b.txt") {
        Some(st) => st,
        None => return Some("stat_b_after_unlink"),
    };
    if unlinked_b.kind != Kind::File || unlinked_b.size != 5 || unlinked_b.nlink != 1 {
        return Some("nlink_b_after_unlink");
    }

    None
}
