// Auto-generated by v155_multi_feature_namespace_procfd_fix.
#![allow(unused_assignments)]
#![allow(dead_code)]
#![allow(static_mut_refs)]

const MAX_NODES: usize = 64;
const MAX_FDS: usize = 40;
const NAME_MAX: usize = 32;
const DATA_MAX: usize = 192;
const TARGET_MAX: usize = 96;
const ROOT: usize = 1;
const AT_FDCWD: isize = -100;

pub const O_CREAT: u32 = 0x40;
pub const O_TRUNC: u32 = 0x200;
pub const O_APPEND: u32 = 0x400;
pub const O_DIRECTORY: u32 = 0x10000;
pub const O_CLOEXEC: u32 = 0x80000;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const R_OK: u32 = 4;
pub const W_OK: u32 = 2;
pub const X_OK: u32 = 1;

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum Errno { NoEnt, Exist, BadFd, NotDir, IsDir, Inval, NoSpace, NotEmpty, Access, Loop }
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum NodeKind { Empty, Dir, File, Symlink }
#[derive(Copy, Clone)]
pub struct MiniStat { pub kind: NodeKind, pub size: usize, pub nlink: u16, pub mode: u16 }
#[derive(Copy, Clone)]
pub struct MiniStatFs { pub files: usize, pub free_files: usize, pub fds_used: usize, pub cwd: usize }

#[derive(Copy, Clone)]
struct Node { used: bool, kind: NodeKind, parent: usize, name: [u8; NAME_MAX], name_len: usize, mode: u16, owner: usize, data: [u8; DATA_MAX], size: usize, target: [u8; TARGET_MAX], target_len: usize }
impl Node { const fn empty() -> Self { Self { used: false, kind: NodeKind::Empty, parent: 0, name: [0; NAME_MAX], name_len: 0, mode: 0, owner: 0, data: [0; DATA_MAX], size: 0, target: [0; TARGET_MAX], target_len: 0 } } }
#[derive(Copy, Clone)]
struct Fd { used: bool, node: usize, off: usize, flags: u32, cloexec: bool }
impl Fd { const fn empty() -> Self { Self { used: false, node: 0, off: 0, flags: 0, cloexec: false } } }

pub struct NamespaceCore { nodes: [Node; MAX_NODES], fds: [Fd; MAX_FDS], cwd: usize, root: usize, umask: u16 }

impl NamespaceCore {
    pub const fn new() -> Self { Self { nodes: [Node::empty(); MAX_NODES], fds: [Fd::empty(); MAX_FDS], cwd: ROOT, root: ROOT, umask: 0o022 } }
    pub fn reset(&mut self) {
        self.nodes = [Node::empty(); MAX_NODES]; self.fds = [Fd::empty(); MAX_FDS]; self.cwd = ROOT; self.root = ROOT; self.umask = 0o022;
        self.nodes[ROOT].used = true; self.nodes[ROOT].kind = NodeKind::Dir; self.nodes[ROOT].parent = ROOT; self.nodes[ROOT].mode = 0o755; self.nodes[ROOT].name[0] = b'/'; self.nodes[ROOT].name_len = 1;
    }
    fn is_dot(name: &[u8]) -> bool { name.len() == 1 && name[0] == b'.' }
    fn is_dotdot(name: &[u8]) -> bool { name.len() == 2 && name[0] == b'.' && name[1] == b'.' }
    fn is_abs(path: &[u8]) -> bool { !path.is_empty() && path[0] == b'/' }
    fn same_name(n: &Node, name: &[u8]) -> bool { if n.name_len != name.len(){return false;} let mut i=0; while i<name.len(){ if n.name[i]!=name[i]{return false;} i+=1;} true }
    fn set_name(n: &mut Node, name: &[u8]) -> Result<(), Errno> { if name.is_empty()||name.len()>NAME_MAX||Self::is_dot(name)||Self::is_dotdot(name){return Err(Errno::Inval);} n.name=[0;NAME_MAX]; n.name_len=name.len(); let mut i=0; while i<name.len(){n.name[i]=name[i]; i+=1;} Ok(()) }
    fn alloc_node(&mut self) -> Result<usize, Errno> { let mut i=2; while i<MAX_NODES { if !self.nodes[i].used { self.nodes[i]=Node::empty(); self.nodes[i].used=true; return Ok(i); } i+=1; } Err(Errno::NoSpace) }
    fn owner(&self, node: usize) -> usize { if self.nodes[node].owner == 0 { node } else { self.nodes[node].owner } }
    fn fd_idx(&self, fd: isize) -> Result<usize, Errno> { if fd<0 {return Err(Errno::BadFd);} let idx=fd as usize; if idx>=MAX_FDS || !self.fds[idx].used {return Err(Errno::BadFd);} Ok(idx) }
    fn start_dir(&self, dirfd: isize, path: &[u8]) -> Result<usize, Errno> { if Self::is_abs(path){return Ok(self.root);} if dirfd==AT_FDCWD {return Ok(self.cwd);} let idx=self.fd_idx(dirfd)?; let node=self.fds[idx].node; if self.nodes[node].kind!=NodeKind::Dir {return Err(Errno::NotDir);} Ok(node) }
    pub fn find_child(&self, parent: usize, name: &[u8]) -> Option<usize> { let mut i=1; while i<MAX_NODES { if self.nodes[i].used && self.nodes[i].parent==parent && Self::same_name(&self.nodes[i], name){return Some(i);} i+=1; } None }
    fn next_component(path: &[u8], mut pos: usize, out: &mut [u8; NAME_MAX]) -> Option<(usize, usize)> { while pos<path.len() && path[pos]==b'/' {pos+=1;} if pos>=path.len(){return None;} let mut len=0; while pos<path.len() && path[pos]!=b'/' { if len>=NAME_MAX {return Some((usize::MAX, usize::MAX));} out[len]=path[pos]; len+=1; pos+=1; } Some((pos,len)) }
    pub fn resolve_at(&self, dirfd: isize, path: &[u8], _follow_final: bool) -> Result<usize, Errno> {
        if path.is_empty(){return Err(Errno::NoEnt);} let mut cur=self.start_dir(dirfd,path)?; let mut pos=0; let mut comp=[0u8;NAME_MAX];
        loop { comp=[0;NAME_MAX]; let (npos,len)=match Self::next_component(path,pos,&mut comp){Some(v)=>v,None=>return Ok(cur)}; if len==usize::MAX{return Err(Errno::Inval);} pos=npos; let name=&comp[..len]; if Self::is_dot(name){continue;} if Self::is_dotdot(name){cur=self.nodes[cur].parent; continue;} if self.nodes[cur].kind!=NodeKind::Dir{return Err(Errno::NotDir);} let child=match self.find_child(cur,name){Some(n)=>n,None=>return Err(Errno::NoEnt)}; cur=child; }
    }
    fn resolve_parent_at(&self, dirfd: isize, path: &[u8], out: &mut [u8; NAME_MAX]) -> Result<(usize, usize), Errno> {
        if path.is_empty(){return Err(Errno::NoEnt);} let mut cur=self.start_dir(dirfd,path)?; let mut pos=0; let mut comp=[0u8;NAME_MAX]; let mut last=[0u8;NAME_MAX]; let mut last_len=0;
        loop { comp=[0;NAME_MAX]; let (npos,len)=match Self::next_component(path,pos,&mut comp){Some(v)=>v,None=>break}; if len==usize::MAX{return Err(Errno::Inval);} let final_comp=Self::next_component(path,npos,&mut [0u8;NAME_MAX]).is_none(); if final_comp { if Self::is_dot(&comp[..len])||Self::is_dotdot(&comp[..len]){return Err(Errno::Inval);} let mut i=0; while i<len {last[i]=comp[i]; i+=1;} last_len=len; break; } let name=&comp[..len]; pos=npos; if Self::is_dot(name){continue;} if Self::is_dotdot(name){cur=self.nodes[cur].parent; continue;} let child=match self.find_child(cur,name){Some(n)=>n,None=>return Err(Errno::NoEnt)}; if self.nodes[child].kind!=NodeKind::Dir{return Err(Errno::NotDir);} cur=child; }
        if last_len==0{return Err(Errno::NoEnt);} let mut i=0; while i<last_len {out[i]=last[i]; i+=1;} Ok((cur,last_len))
    }
    pub fn mkdirat(&mut self, dirfd:isize, path:&[u8], mode:u16)->Result<usize,Errno>{ let mut name=[0u8;NAME_MAX]; let (parent,len)=self.resolve_parent_at(dirfd,path,&mut name)?; if self.find_child(parent,&name[..len]).is_some(){return Err(Errno::Exist);} let n=self.alloc_node()?; self.nodes[n].kind=NodeKind::Dir; self.nodes[n].parent=parent; self.nodes[n].mode=mode & !self.umask & 0o777; Self::set_name(&mut self.nodes[n],&name[..len])?; Ok(n) }
    fn create_file_at(&mut self, dirfd:isize, path:&[u8], mode:u16)->Result<usize,Errno>{ let mut name=[0u8;NAME_MAX]; let (parent,len)=self.resolve_parent_at(dirfd,path,&mut name)?; if self.find_child(parent,&name[..len]).is_some(){return Err(Errno::Exist);} let n=self.alloc_node()?; self.nodes[n].kind=NodeKind::File; self.nodes[n].parent=parent; self.nodes[n].mode=mode & !self.umask & 0o777; Self::set_name(&mut self.nodes[n],&name[..len])?; Ok(n) }
    pub fn openat(&mut self, dirfd:isize, path:&[u8], flags:u32, mode:u16)->Result<isize,Errno>{ let node=match self.resolve_at(dirfd,path,true){Ok(n)=>n,Err(Errno::NoEnt) if (flags&O_CREAT)!=0=>self.create_file_at(dirfd,path,mode)?,Err(e)=>return Err(e)}; if (flags&O_DIRECTORY)!=0 && self.nodes[node].kind!=NodeKind::Dir{return Err(Errno::NotDir);} if self.nodes[node].kind==NodeKind::Dir && (flags&O_DIRECTORY)==0{return Err(Errno::IsDir);} let owner=self.owner(node); if self.nodes[owner].kind==NodeKind::File && (flags&O_TRUNC)!=0{self.nodes[owner].size=0;} let mut fd=3; while fd<MAX_FDS { if !self.fds[fd].used { let off=if (flags&O_APPEND)!=0 && self.nodes[owner].kind==NodeKind::File {self.nodes[owner].size}else{0}; self.fds[fd]=Fd{used:true,node,off,flags,cloexec:(flags&O_CLOEXEC)!=0}; return Ok(fd as isize);} fd+=1;} Err(Errno::NoSpace) }
    pub fn close(&mut self, fd:isize)->Result<(),Errno>{let i=self.fd_idx(fd)?; self.fds[i]=Fd::empty(); Ok(())}
    pub fn chdir(&mut self,path:&[u8])->Result<(),Errno>{let n=self.resolve_at(AT_FDCWD,path,true)?; if self.nodes[n].kind!=NodeKind::Dir{return Err(Errno::NotDir);} self.cwd=n; Ok(())}
    pub fn fchdir(&mut self,fd:isize)->Result<(),Errno>{let i=self.fd_idx(fd)?; let n=self.fds[i].node; if self.nodes[n].kind!=NodeKind::Dir{return Err(Errno::NotDir);} self.cwd=n; Ok(())}
    pub fn getcwd_contains(&self, needle:&[u8])->bool{let mut n=self.cwd; while n!=self.root {if Self::same_name(&self.nodes[n],needle){return true;} n=self.nodes[n].parent;} false}
    pub fn write(&mut self,fd:isize,src:&[u8])->Result<usize,Errno>{let i=self.fd_idx(fd)?; let owner=self.owner(self.fds[i].node); if self.nodes[owner].kind!=NodeKind::File{return Err(Errno::IsDir);} if (self.fds[i].flags&O_APPEND)!=0{self.fds[i].off=self.nodes[owner].size;} let mut pos=self.fds[i].off; let mut n=0; while n<src.len() && pos<DATA_MAX{self.nodes[owner].data[pos]=src[n]; pos+=1; n+=1;} if pos>self.nodes[owner].size{self.nodes[owner].size=pos;} self.fds[i].off=pos; Ok(n)}
    pub fn read(&mut self,fd:isize,out:&mut [u8])->Result<usize,Errno>{let i=self.fd_idx(fd)?; let owner=self.owner(self.fds[i].node); if self.nodes[owner].kind!=NodeKind::File{return Err(Errno::IsDir);} let mut pos=self.fds[i].off; let mut n=0; while n<out.len() && pos<self.nodes[owner].size{out[n]=self.nodes[owner].data[pos]; n+=1; pos+=1;} self.fds[i].off=pos; Ok(n)}
    pub fn lseek(&mut self,fd:isize,off:isize,whence:u32)->Result<usize,Errno>{let i=self.fd_idx(fd)?; let owner=self.owner(self.fds[i].node); let base=match whence{SEEK_SET=>0,SEEK_CUR=>self.fds[i].off as isize,SEEK_END=>self.nodes[owner].size as isize,_=>return Err(Errno::Inval)}; let next=base+off; if next<0{return Err(Errno::Inval);} self.fds[i].off=next as usize; Ok(self.fds[i].off)}
    pub fn dup3(&mut self,oldfd:isize,newfd:isize,cloexec:bool)->Result<isize,Errno>{let old=self.fd_idx(oldfd)?; if newfd<0 || newfd as usize>=MAX_FDS{return Err(Errno::BadFd);} let new=newfd as usize; self.fds[new]=self.fds[old]; self.fds[new].cloexec=cloexec; Ok(newfd)}
    pub fn exec_close_cloexec(&mut self)->usize{let mut c=0; let mut i=0; while i<MAX_FDS{if self.fds[i].used && self.fds[i].cloexec{self.fds[i]=Fd::empty(); c+=1;} i+=1;} c}
    pub fn linkat(&mut self,olddir:isize,oldpath:&[u8],newdir:isize,newpath:&[u8])->Result<usize,Errno>{let old=self.resolve_at(olddir,oldpath,true)?; let owner=self.owner(old); if self.nodes[owner].kind!=NodeKind::File{return Err(Errno::Inval);} let mut name=[0u8;NAME_MAX]; let (parent,len)=self.resolve_parent_at(newdir,newpath,&mut name)?; if self.find_child(parent,&name[..len]).is_some(){return Err(Errno::Exist);} let n=self.alloc_node()?; self.nodes[n].kind=NodeKind::File; self.nodes[n].parent=parent; self.nodes[n].owner=owner; self.nodes[n].mode=self.nodes[owner].mode; Self::set_name(&mut self.nodes[n],&name[..len])?; Ok(n)}
    pub fn renameat(&mut self,olddir:isize,oldpath:&[u8],newdir:isize,newpath:&[u8])->Result<(),Errno>{let node=self.resolve_at(olddir,oldpath,false)?; let mut name=[0u8;NAME_MAX]; let (parent,len)=self.resolve_parent_at(newdir,newpath,&mut name)?; if let Some(v)=self.find_child(parent,&name[..len]){self.nodes[v].used=false;} self.nodes[node].parent=parent; Self::set_name(&mut self.nodes[node],&name[..len])}
    pub fn unlinkat(&mut self,dirfd:isize,path:&[u8])->Result<(),Errno>{let n=self.resolve_at(dirfd,path,false)?; if self.nodes[n].kind==NodeKind::Dir{return Err(Errno::IsDir);} if n==ROOT{return Err(Errno::Inval);} self.nodes[n].used=false; Ok(())}
    pub fn rmdir(&mut self,dirfd:isize,path:&[u8])->Result<(),Errno>{let n=self.resolve_at(dirfd,path,true)?; if self.nodes[n].kind!=NodeKind::Dir{return Err(Errno::NotDir);} let mut i=1; while i<MAX_NODES{if self.nodes[i].used && self.nodes[i].parent==n && i!=n{return Err(Errno::NotEmpty);} i+=1;} if n==ROOT{return Err(Errno::Inval);} self.nodes[n].used=false; Ok(())}
    pub fn symlinkat(&mut self,target:&[u8],newdir:isize,newpath:&[u8])->Result<usize,Errno>{if target.is_empty()||target.len()>TARGET_MAX{return Err(Errno::Inval);} let mut name=[0u8;NAME_MAX]; let (parent,len)=self.resolve_parent_at(newdir,newpath,&mut name)?; if self.find_child(parent,&name[..len]).is_some(){return Err(Errno::Exist);} let n=self.alloc_node()?; self.nodes[n].kind=NodeKind::Symlink; self.nodes[n].parent=parent; self.nodes[n].mode=0o777; Self::set_name(&mut self.nodes[n],&name[..len])?; let mut i=0; while i<target.len(){self.nodes[n].target[i]=target[i]; i+=1;} self.nodes[n].target_len=target.len(); Ok(n)}
    pub fn readlinkat(&self,dirfd:isize,path:&[u8],out:&mut [u8])->Result<usize,Errno>{let n=self.resolve_at(dirfd,path,false)?; if self.nodes[n].kind!=NodeKind::Symlink{return Err(Errno::Inval);} let mut i=0; while i<out.len() && i<self.nodes[n].target_len{out[i]=self.nodes[n].target[i]; i+=1;} Ok(i)}
    pub fn chmod(&mut self,dirfd:isize,path:&[u8],mode:u16)->Result<(),Errno>{let n=self.resolve_at(dirfd,path,true)?; let owner=self.owner(n); self.nodes[owner].mode=mode&0o777; Ok(())}
    pub fn access(&self,dirfd:isize,path:&[u8],mask:u32)->Result<(),Errno>{let n=self.resolve_at(dirfd,path,true)?; let owner=self.owner(n); let mode=self.nodes[owner].mode; if (mask&R_OK)!=0 && (mode&0o444)==0{return Err(Errno::Access);} if (mask&W_OK)!=0 && (mode&0o222)==0{return Err(Errno::Access);} if (mask&X_OK)!=0 && (mode&0o111)==0{return Err(Errno::Access);} Ok(())}
    pub fn stat(&self,dirfd:isize,path:&[u8],follow:bool)->Result<MiniStat,Errno>{let n=self.resolve_at(dirfd,path,follow)?; let owner=self.owner(n); let mut nlink=0u16; let mut i=1; while i<MAX_NODES{if self.nodes[i].used && self.nodes[i].kind==NodeKind::File && self.owner(i)==owner{nlink+=1;} i+=1;} if self.nodes[n].kind!=NodeKind::File{nlink=1;} let size=match self.nodes[n].kind{NodeKind::File=>self.nodes[owner].size,NodeKind::Symlink=>self.nodes[n].target_len,_=>0}; Ok(MiniStat{kind:self.nodes[n].kind,size,nlink,mode:self.nodes[owner].mode})}
    pub fn getdents_count(&self,dirfd:isize)->Result<usize,Errno>{let idx=self.fd_idx(dirfd)?; let dir=self.fds[idx].node; if self.nodes[dir].kind!=NodeKind::Dir{return Err(Errno::NotDir);} let mut c=0; let mut i=1; while i<MAX_NODES{if self.nodes[i].used && self.nodes[i].parent==dir && i!=dir{c+=1;} i+=1;} Ok(c)}
    pub fn statfs(&self)->MiniStatFs{let mut files=0; let mut fds=0; let mut i=1; while i<MAX_NODES{if self.nodes[i].used{files+=1;} i+=1;} i=0; while i<MAX_FDS{if self.fds[i].used{fds+=1;} i+=1;} MiniStatFs{files,free_files:MAX_NODES-files,fds_used:fds,cwd:self.cwd}}
}

static mut V155_NS: NamespaceCore = NamespaceCore::new();
fn bytes_eq(a:&[u8],b:&[u8])->bool{if a.len()!=b.len(){return false;} let mut i=0; while i<a.len(){if a[i]!=b[i]{return false;} i+=1;} true}

pub fn run_v155_namespace_procfd_scenario() -> Option<&'static str> {
    let fs=unsafe{&mut V155_NS}; fs.reset();
    if fs.mkdirat(AT_FDCWD,b"v155root",0o755).is_err(){return Some("mkdir_root");}
    if fs.chdir(b"v155root").is_err(){return Some("chdir_root");}
    if !fs.getcwd_contains(b"v155root"){return Some("getcwd_root");}
    if fs.mkdirat(AT_FDCWD,b"sub",0o755).is_err(){return Some("mkdir_sub");}
    if fs.mkdirat(AT_FDCWD,b"sub/inner",0o755).is_err(){return Some("mkdir_inner");}
    let rootfd=match fs.openat(AT_FDCWD,b".",O_DIRECTORY,0){Ok(fd)=>fd,Err(_)=>return Some("open_dot_dir")};
    let subfd=match fs.openat(rootfd,b"sub",O_DIRECTORY,0){Ok(fd)=>fd,Err(_)=>return Some("open_sub_dirfd")};
    if fs.fchdir(subfd).is_err(){return Some("fchdir_sub");}
    if fs.mkdirat(AT_FDCWD,b"../logs",0o755).is_err(){return Some("mkdir_dotdot_logs");}
    if fs.fchdir(rootfd).is_err(){return Some("fchdir_root");}
    let fd=match fs.openat(rootfd,b"logs/a.txt",O_CREAT,0o644){Ok(fd)=>fd,Err(_)=>return Some("open_create_a")};
    if fs.write(fd,b"alpha").ok()!=Some(5){return Some("write_alpha");}
    if fs.lseek(fd,2,SEEK_SET).ok()!=Some(2){return Some("seek_alpha");}
    if fs.write(fd,b"XYZ").ok()!=Some(3){return Some("overwrite_alpha");}
    if fs.lseek(fd,0,SEEK_SET).is_err(){return Some("seek_readback");}
    let mut buf=[0u8;16]; let n=match fs.read(fd,&mut buf){Ok(n)=>n,Err(_)=>return Some("read_alpha")};
    if !bytes_eq(&buf[..n],b"alXYZ"){return Some("alpha_content");}
    if fs.close(fd).is_err(){return Some("close_alpha");}
    let app=match fs.openat(rootfd,b"logs/a.txt",O_APPEND,0){Ok(fd)=>fd,Err(_)=>return Some("open_append")};
    if fs.write(app,b"+").ok()!=Some(1){return Some("append_plus");}
    let clo=match fs.dup3(app,31,true){Ok(fd)=>fd,Err(_)=>return Some("dup_cloexec")};
    if fs.write(clo,b"!").ok()!=Some(1){return Some("write_dup");}
    if fs.exec_close_cloexec()==0{return Some("exec_cloexec");}
    if fs.write(clo,b"x").err()!=Some(Errno::BadFd){return Some("cloexec_closed");}
    if fs.close(app).is_err(){return Some("close_app");}
    if fs.linkat(rootfd,b"logs/a.txt",rootfd,b"logs/hard_a.txt").is_err(){return Some("link_hard");}
    let st=match fs.stat(rootfd,b"logs/hard_a.txt",true){Ok(s)=>s,Err(_)=>return Some("stat_hard")};
    if st.nlink!=2 || st.size!=7{return Some("hard_stat");}
    if fs.renameat(rootfd,b"logs/a.txt",rootfd,b"logs/renamed.txt").is_err(){return Some("rename_a");}
    if fs.stat(rootfd,b"logs/a.txt",true).err()!=Some(Errno::NoEnt){return Some("old_name_gone");}
    if fs.symlinkat(b"logs/renamed.txt",rootfd,b"sym_renamed").is_err(){return Some("symlink");}
    let mut target=[0u8;32]; let tn=match fs.readlinkat(rootfd,b"sym_renamed",&mut target){Ok(n)=>n,Err(_)=>return Some("readlink")};
    if !bytes_eq(&target[..tn],b"logs/renamed.txt"){return Some("readlink_target");}
    let nested=match fs.openat(rootfd,b"sub/inner/nested.txt",O_CREAT|O_TRUNC,0o600){Ok(fd)=>fd,Err(_)=>return Some("open_nested")};
    if fs.write(nested,b"nested").ok()!=Some(6){return Some("write_nested");}
    if fs.lseek(nested,0,SEEK_SET).is_err(){return Some("seek_nested");}
    let mut nbuf=[0u8;16]; let nn=match fs.read(nested,&mut nbuf){Ok(n)=>n,Err(_)=>return Some("read_nested")};
    if !bytes_eq(&nbuf[..nn],b"nested"){return Some("nested_content");}
    if fs.rmdir(rootfd,b"sub/inner").err()!=Some(Errno::NotEmpty){return Some("rmdir_notempty");}
    if fs.unlinkat(rootfd,b"sub/inner/nested.txt").is_err(){return Some("unlink_nested");}
    if fs.rmdir(rootfd,b"sub/inner").is_err(){return Some("rmdir_inner");}
    if fs.chmod(rootfd,b"logs/renamed.txt",0o444).is_err(){return Some("chmod_readonly");}
    if fs.access(rootfd,b"logs/renamed.txt",W_OK).err()!=Some(Errno::Access){return Some("access_write_denied");}
    if fs.access(rootfd,b"logs/renamed.txt",R_OK).is_err(){return Some("access_read_ok");}
    let dircount=match fs.getdents_count(rootfd){Ok(v)=>v,Err(_)=>return Some("getdents_root")};
    if dircount<3{return Some("getdents_count");}
    let sfs=fs.statfs(); if sfs.files<5 || sfs.free_files==0 || sfs.fds_used==0{return Some("statfs");}
    None
}
