// Auto-generated by v154_multi_feature_fs_core_fix.
// Heapless FS/VFS semantic core: inode table, fd table, offsets, links, symlinks,
// metadata, and permission checks. This is implementation code; active_once only
// verifies it so previous runtime paths remain protected.
#![allow(dead_code)]
#![allow(static_mut_refs)]

const MAX_NODES: usize = 48;
const MAX_FDS: usize = 32;
const NAME_MAX: usize = 32;
const DATA_MAX: usize = 192;
const TARGET_MAX: usize = 64;
const ROOT: usize = 1;

pub const O_APPEND: u32 = 0x400;
pub const O_TRUNC: u32 = 0x200;
pub const F_GETFL: u32 = 3;
pub const F_SETFL: u32 = 4;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const R_OK: u32 = 4;
pub const W_OK: u32 = 2;
pub const X_OK: u32 = 1;

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum FsError { NoEnt, Exist, BadFd, NotDir, IsDir, Inval, NoSpace, Access }

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum NodeKind { Empty, Dir, File, Symlink }

#[derive(Copy, Clone)]
pub struct MiniStat { pub kind: NodeKind, pub size: usize, pub nlink: u16, pub mode: u16 }

#[derive(Copy, Clone)]
struct Node {
    used: bool,
    kind: NodeKind,
    parent: usize,
    name: [u8; NAME_MAX],
    name_len: usize,
    mode: u16,
    owner: usize,
    data: [u8; DATA_MAX],
    size: usize,
    target: [u8; TARGET_MAX],
    target_len: usize,
}

impl Node {
    const fn empty() -> Self {
        Self { used: false, kind: NodeKind::Empty, parent: 0, name: [0; NAME_MAX], name_len: 0, mode: 0, owner: 0, data: [0; DATA_MAX], size: 0, target: [0; TARGET_MAX], target_len: 0 }
    }
}

#[derive(Copy, Clone)]
struct Fd { used: bool, node: usize, off: usize, flags: u32, cloexec: bool }
impl Fd { const fn empty() -> Self { Self { used: false, node: 0, off: 0, flags: 0, cloexec: false } } }

pub struct FsCore { nodes: [Node; MAX_NODES], fds: [Fd; MAX_FDS], cwd: usize }

impl FsCore {
    pub const fn new() -> Self { Self { nodes: [Node::empty(); MAX_NODES], fds: [Fd::empty(); MAX_FDS], cwd: ROOT } }

    pub fn reset(&mut self) {
        self.nodes = [Node::empty(); MAX_NODES];
        self.fds = [Fd::empty(); MAX_FDS];
        self.cwd = ROOT;
        self.nodes[ROOT].used = true;
        self.nodes[ROOT].kind = NodeKind::Dir;
        self.nodes[ROOT].parent = ROOT;
        self.nodes[ROOT].mode = 0o755;
        self.nodes[ROOT].name[0] = b'/';
        self.nodes[ROOT].name_len = 1;
    }

    fn same_name(n: &Node, name: &[u8]) -> bool {
        if n.name_len != name.len() { return false; }
        let mut i = 0;
        while i < name.len() { if n.name[i] != name[i] { return false; } i += 1; }
        true
    }

    fn set_name(n: &mut Node, name: &[u8]) -> Result<(), FsError> {
        if name.is_empty() || name.len() > NAME_MAX { return Err(FsError::Inval); }
        n.name = [0; NAME_MAX];
        n.name_len = name.len();
        let mut i = 0;
        while i < name.len() { n.name[i] = name[i]; i += 1; }
        Ok(())
    }

    fn alloc_node(&mut self) -> Result<usize, FsError> {
        let mut i = 2;
        while i < MAX_NODES {
            if !self.nodes[i].used { self.nodes[i] = Node::empty(); self.nodes[i].used = true; return Ok(i); }
            i += 1;
        }
        Err(FsError::NoSpace)
    }

    fn owner(&self, node: usize) -> usize { if self.nodes[node].owner == 0 { node } else { self.nodes[node].owner } }

    pub fn find_child(&self, parent: usize, name: &[u8]) -> Option<usize> {
        let mut i = 1;
        while i < MAX_NODES {
            if self.nodes[i].used && self.nodes[i].parent == parent && Self::same_name(&self.nodes[i], name) { return Some(i); }
            i += 1;
        }
        None
    }

    pub fn mkdir_child(&mut self, parent: usize, name: &[u8], mode: u16) -> Result<usize, FsError> {
        if self.nodes[parent].kind != NodeKind::Dir { return Err(FsError::NotDir); }
        if self.find_child(parent, name).is_some() { return Err(FsError::Exist); }
        let node = self.alloc_node()?;
        self.nodes[node].kind = NodeKind::Dir;
        self.nodes[node].parent = parent;
        self.nodes[node].mode = mode & 0o777;
        Self::set_name(&mut self.nodes[node], name)?;
        Ok(node)
    }

    pub fn create_file(&mut self, parent: usize, name: &[u8], mode: u16) -> Result<usize, FsError> {
        if self.nodes[parent].kind != NodeKind::Dir { return Err(FsError::NotDir); }
        if self.find_child(parent, name).is_some() { return Err(FsError::Exist); }
        let node = self.alloc_node()?;
        self.nodes[node].kind = NodeKind::File;
        self.nodes[node].parent = parent;
        self.nodes[node].mode = mode & 0o777;
        Self::set_name(&mut self.nodes[node], name)?;
        Ok(node)
    }

    pub fn rename_child(&mut self, node: usize, new_parent: usize, new_name: &[u8]) -> Result<(), FsError> {
        if !self.nodes[node].used || self.nodes[new_parent].kind != NodeKind::Dir { return Err(FsError::NoEnt); }
        if let Some(old) = self.find_child(new_parent, new_name) { self.nodes[old].used = false; }
        self.nodes[node].parent = new_parent;
        Self::set_name(&mut self.nodes[node], new_name)
    }

    pub fn link_child(&mut self, existing: usize, parent: usize, name: &[u8]) -> Result<usize, FsError> {
        if self.nodes[existing].kind != NodeKind::File { return Err(FsError::Inval); }
        if self.find_child(parent, name).is_some() { return Err(FsError::Exist); }
        let owner = self.owner(existing);
        let node = self.alloc_node()?;
        self.nodes[node].kind = NodeKind::File;
        self.nodes[node].parent = parent;
        self.nodes[node].mode = self.nodes[owner].mode;
        self.nodes[node].owner = owner;
        Self::set_name(&mut self.nodes[node], name)?;
        Ok(node)
    }

    pub fn unlink_child(&mut self, node: usize) -> Result<(), FsError> {
        if node == ROOT || !self.nodes[node].used { return Err(FsError::Inval); }
        self.nodes[node].used = false;
        Ok(())
    }

    pub fn symlink_child(&mut self, parent: usize, name: &[u8], target: &[u8]) -> Result<usize, FsError> {
        if target.is_empty() || target.len() > TARGET_MAX { return Err(FsError::Inval); }
        if self.find_child(parent, name).is_some() { return Err(FsError::Exist); }
        let node = self.alloc_node()?;
        self.nodes[node].kind = NodeKind::Symlink;
        self.nodes[node].parent = parent;
        self.nodes[node].mode = 0o777;
        Self::set_name(&mut self.nodes[node], name)?;
        let mut i = 0; while i < target.len() { self.nodes[node].target[i] = target[i]; i += 1; }
        self.nodes[node].target_len = target.len();
        Ok(node)
    }

    pub fn readlink(&self, node: usize, out: &mut [u8]) -> Result<usize, FsError> {
        if self.nodes[node].kind != NodeKind::Symlink { return Err(FsError::Inval); }
        let mut i = 0;
        while i < out.len() && i < self.nodes[node].target_len { out[i] = self.nodes[node].target[i]; i += 1; }
        Ok(i)
    }

    pub fn open_node(&mut self, node: usize, flags: u32) -> Result<isize, FsError> {
        if !self.nodes[node].used { return Err(FsError::NoEnt); }
        if self.nodes[node].kind == NodeKind::Dir { return Err(FsError::IsDir); }
        let owner = self.owner(node);
        if (flags & O_TRUNC) != 0 && self.nodes[owner].kind == NodeKind::File { self.nodes[owner].size = 0; }
        let mut fd = 3;
        while fd < MAX_FDS {
            if !self.fds[fd].used {
                let off = if (flags & O_APPEND) != 0 { self.nodes[owner].size } else { 0 };
                self.fds[fd] = Fd { used: true, node, off, flags, cloexec: false };
                return Ok(fd as isize);
            }
            fd += 1;
        }
        Err(FsError::NoSpace)
    }

    fn fd_idx(&self, fd: isize) -> Result<usize, FsError> {
        if fd < 0 { return Err(FsError::BadFd); }
        let idx = fd as usize;
        if idx >= MAX_FDS || !self.fds[idx].used { return Err(FsError::BadFd); }
        Ok(idx)
    }

    pub fn close(&mut self, fd: isize) -> Result<(), FsError> { let i = self.fd_idx(fd)?; self.fds[i] = Fd::empty(); Ok(()) }

    pub fn write(&mut self, fd: isize, src: &[u8]) -> Result<usize, FsError> {
        let idx = self.fd_idx(fd)?;
        let owner = self.owner(self.fds[idx].node);
        if (self.fds[idx].flags & O_APPEND) != 0 { self.fds[idx].off = self.nodes[owner].size; }
        let mut pos = self.fds[idx].off;
        let mut n = 0;
        while n < src.len() && pos < DATA_MAX { self.nodes[owner].data[pos] = src[n]; pos += 1; n += 1; }
        if pos > self.nodes[owner].size { self.nodes[owner].size = pos; }
        self.fds[idx].off = pos;
        Ok(n)
    }

    pub fn read(&mut self, fd: isize, out: &mut [u8]) -> Result<usize, FsError> {
        let idx = self.fd_idx(fd)?;
        let owner = self.owner(self.fds[idx].node);
        let mut pos = self.fds[idx].off;
        let mut n = 0;
        while n < out.len() && pos < self.nodes[owner].size { out[n] = self.nodes[owner].data[pos]; pos += 1; n += 1; }
        self.fds[idx].off = pos;
        Ok(n)
    }

    pub fn lseek(&mut self, fd: isize, off: isize, whence: u32) -> Result<usize, FsError> {
        let idx = self.fd_idx(fd)?;
        let owner = self.owner(self.fds[idx].node);
        let base = match whence { SEEK_SET => 0, SEEK_CUR => self.fds[idx].off as isize, SEEK_END => self.nodes[owner].size as isize, _ => return Err(FsError::Inval) };
        let next = base + off;
        if next < 0 { return Err(FsError::Inval); }
        self.fds[idx].off = next as usize;
        Ok(self.fds[idx].off)
    }

    pub fn dup3(&mut self, oldfd: isize, newfd: isize, cloexec: bool) -> Result<isize, FsError> {
        let old = self.fd_idx(oldfd)?;
        if newfd < 0 || newfd as usize >= MAX_FDS { return Err(FsError::BadFd); }
        let new = newfd as usize;
        self.fds[new] = self.fds[old];
        self.fds[new].cloexec = cloexec;
        Ok(newfd)
    }

    pub fn fcntl(&mut self, fd: isize, cmd: u32, arg: u32) -> Result<u32, FsError> {
        let idx = self.fd_idx(fd)?;
        match cmd { F_GETFL => Ok(self.fds[idx].flags), F_SETFL => { self.fds[idx].flags = arg; Ok(0) }, _ => Err(FsError::Inval) }
    }

    pub fn stat(&self, node: usize) -> Result<MiniStat, FsError> {
        if !self.nodes[node].used { return Err(FsError::NoEnt); }
        let owner = self.owner(node);
        let mut nlink = 0u16;
        let mut i = 1;
        while i < MAX_NODES { if self.nodes[i].used && self.nodes[i].kind == NodeKind::File && self.owner(i) == owner { nlink += 1; } i += 1; }
        if self.nodes[node].kind != NodeKind::File { nlink = 1; }
        let size = match self.nodes[node].kind { NodeKind::File => self.nodes[owner].size, NodeKind::Symlink => self.nodes[node].target_len, _ => 0 };
        Ok(MiniStat { kind: self.nodes[node].kind, size, nlink, mode: self.nodes[owner].mode })
    }

    pub fn chmod(&mut self, node: usize, mode: u16) -> Result<(), FsError> { let owner = self.owner(node); self.nodes[owner].mode = mode & 0o777; Ok(()) }

    pub fn access(&self, node: usize, mask: u32) -> Result<(), FsError> {
        let owner = self.owner(node); let mode = self.nodes[owner].mode;
        if (mask & R_OK) != 0 && (mode & 0o444) == 0 { return Err(FsError::Access); }
        if (mask & W_OK) != 0 && (mode & 0o222) == 0 { return Err(FsError::Access); }
        if (mask & X_OK) != 0 && (mode & 0o111) == 0 { return Err(FsError::Access); }
        Ok(())
    }

    pub fn getdents_count(&self, parent: usize) -> Result<usize, FsError> {
        if self.nodes[parent].kind != NodeKind::Dir { return Err(FsError::NotDir); }
        let mut c = 0; let mut i = 1;
        while i < MAX_NODES { if self.nodes[i].used && self.nodes[i].parent == parent && i != parent { c += 1; } i += 1; }
        Ok(c)
    }
}

static mut V154_FS: FsCore = FsCore::new();

fn bytes_eq(a: &[u8], b: &[u8]) -> bool { if a.len()!=b.len(){return false;} let mut i=0; while i<a.len(){ if a[i]!=b[i]{return false;} i+=1;} true }

pub fn run_v154_core_scenario() -> Option<&'static str> {
    let fs = unsafe { &mut V154_FS };
    fs.reset();
    let root = ROOT;
    let v154 = match fs.mkdir_child(root, b"v154root", 0o755) { Ok(n) => n, Err(_) => return Some("mkdir_v154root") };
    let sub = match fs.mkdir_child(v154, b"sub", 0o755) { Ok(n) => n, Err(_) => return Some("mkdir_sub") };
    if fs.mkdir_child(v154, b"sub", 0o755).err() != Some(FsError::Exist) { return Some("mkdir_eexist") }
    let a = match fs.create_file(v154, b"a.txt", 0o644) { Ok(n) => n, Err(_) => return Some("create_a") };
    let afd = match fs.open_node(a, 0) { Ok(fd) => fd, Err(_) => return Some("open_a") };
    if fs.write(afd, b"abcdef").ok() != Some(6) { return Some("write_initial") }
    if fs.lseek(afd, 3, SEEK_SET).ok() != Some(3) { return Some("seek_overwrite") }
    if fs.write(afd, b"XYZ").ok() != Some(3) { return Some("write_overwrite") }
    if fs.lseek(afd, 0, SEEK_SET).is_err() { return Some("seek_readback") }
    let mut buf=[0u8;16]; let n=match fs.read(afd,&mut buf){Ok(v)=>v,Err(_)=>return Some("read_back")};
    if !bytes_eq(&buf[..n], b"abcXYZ") { return Some("overwrite_content") }
    if fs.close(afd).is_err() { return Some("close_a") }
    let appfd = match fs.open_node(a, O_APPEND) { Ok(fd) => fd, Err(_) => return Some("open_append") };
    if fs.write(appfd, b"!").ok()!=Some(1) { return Some("append_write") }
    if fs.close(appfd).is_err() { return Some("close_append") }
    let hard = match fs.link_child(a, v154, b"hard_a.txt") { Ok(n)=>n, Err(_)=>return Some("link_hard") };
    let st = match fs.stat(a) { Ok(s)=>s, Err(_)=>return Some("stat_a") };
    if st.nlink != 2 || st.size != 7 { return Some("stat_nlink_size") }
    if fs.rename_child(a, v154, b"renamed_a.txt").is_err() { return Some("rename_a") }
    if fs.find_child(v154, b"a.txt").is_some() { return Some("old_name_visible") }
    if fs.stat(hard).ok().map(|s|s.nlink) != Some(2) { return Some("hard_nlink_after_rename") }
    let sym = match fs.symlink_child(v154, b"sym_a.txt", b"renamed_a.txt") { Ok(n)=>n, Err(_)=>return Some("symlink") };
    let mut target=[0u8;32]; let tn=match fs.readlink(sym,&mut target){Ok(v)=>v,Err(_)=>return Some("readlink")};
    if !bytes_eq(&target[..tn], b"renamed_a.txt") { return Some("readlink_target") }
    let b = match fs.create_file(sub, b"b.txt", 0o600) { Ok(n)=>n, Err(_)=>return Some("create_b") };
    let bfd = match fs.open_node(b, 0) { Ok(fd)=>fd, Err(_)=>return Some("open_b") };
    if fs.write(bfd, b"bravo!").ok()!=Some(6) { return Some("write_b") }
    let bdup=match fs.dup3(bfd, 27, true){Ok(fd)=>fd,Err(_)=>return Some("dup3")};
    if fs.fcntl(bdup, F_SETFL, O_APPEND).is_err() { return Some("fcntl_setfl") }
    if fs.write(bdup, b"+").ok()!=Some(1) { return Some("dup_append") }
    if fs.lseek(bfd,0,SEEK_SET).is_err() { return Some("seek_b") }
    let mut bbuf=[0u8;16]; let bn=match fs.read(bfd,&mut bbuf){Ok(v)=>v,Err(_)=>return Some("read_b")};
    if !bytes_eq(&bbuf[..bn], b"bravo!+") { return Some("b_content") }
    if fs.getdents_count(v154).ok().unwrap_or(0) < 4 { return Some("getdents_root") }
    if fs.getdents_count(sub).ok().unwrap_or(0) < 1 { return Some("getdents_sub") }
    if fs.chmod(a,0).is_err() { return Some("chmod_zero") }
    if fs.access(a,R_OK).err()!=Some(FsError::Access) { return Some("access_denied") }
    if fs.chmod(a,0o644).is_err() { return Some("chmod_restore") }
    if fs.unlink_child(hard).is_err() { return Some("unlink_hard") }
    if fs.stat(a).ok().map(|s|s.nlink)!=Some(1) { return Some("nlink_after_unlink") }
    let tfd = match fs.open_node(a,O_TRUNC){Ok(fd)=>fd,Err(_)=>return Some("open_trunc")};
    if fs.stat(a).ok().map(|s|s.size)!=Some(0) { return Some("truncate_size") }
    if fs.write(tfd,b"z").ok()!=Some(1) { return Some("write_after_trunc") }
    None
}
